# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

##########################################################################################
# Be sure to edit the values below
##########################################################################################

title: IDManagement.gov
email: icam@gsa.gov
description: IDManagement.gov is a collaboration between the Federal CIO Council and GSA to develop and share leading practices in protecting federal IT systems.
baseurl: ""
repourl: "https://github.com/GSA/idmanagement.gov"

#for site map search
url: https://www.idmanagement.gov

# GitHub information
# This is used for adding an edit this page link to the footer
github_info:
  organization: GSA
  repository: idmanagement.gov
  default_branch: federalist-pages

# Twitter handle. Only the handle, not the URL.
# twitter: 18F
url: "https://www.idmanagement.gov"

dap:
  agency: GSA

  # Optional
  # subagency: your-subagency

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: Home
    description: IDmanagement.gov
    url: /
# WhyFICAM? top level menu with dropdowns
  - name: Why FICAM?
    children:
      - name: Introduction
        url: /why/introduction/
      - name: Architecture
        url: /why/architecture/
      - name: History
        url: /why/history/
      - name: ICAM
        url: /why/icam/
      - name: Goals and Objectives
        url: /why/goals-and-objectives/

      # - name: Identity Management
      #   url: /why/identity-management/
      # - name: Credential Management
      #   url: /why/credential-management/
      # - name: Access Management
      #   url: /why/access-management/
      # - name: Federation
      #   url: /why/federation/
      # - name: Governance
      #   url: /why/governance/
      # - name: Use Cases
      #   url: /why/use-cases/
      # - name: System Component Examples
      #   url: /why/system-component-examples/
      # - name: Authoritative Sources
      #   url: /why/authoritative-sources/
      # - name: Federation Overview
      #   url: /why/federation-overview/

# What is FICAM top level menu with dropdowns
  - name: What is FICAM?
    children: 
      - name: Introduction
        url: /what/introduction/
      - name: Products
        url: /what/products/
      - name: Services
        url: /what/services/
      - name: PIV Details
        url: /what/pivdetails/
      - name: Service Framework
        url: /what/servicesframework/
      - name: Use Cases
        url: /what/usecases/
      # - name: Organizations that offer ICAM services
      #   url: /what/organizations-that-offer-icam-services/
      # - name: Personal Identity Verification (PIV) Cards
      #   url: /what/personal-identity-verification-piv-cards/
      # - name: User Guides
      #   url: /what/user-guides/
      # - name: Physical Access Control System (PACS) 
      #   url: /what/physical-access-control-system-pacs/ 
      # - name: GSA Multiple Award Schedule
      #   url: /what/gsa-multiple-award-schedule/
      # - name: Trust Services
      #   url: /what/trust-services/
      # - name: GSA ICAM Solutions and Shared Services
      #   url: /what/gsa-icam-solutions-and-shared-services/
      # - name: FIPS 201 Removed Product List
      #   url: /what/fips-201-removed-product-list/
      # - name: Credential Management & Overview
      #   url: /what/credential-management-overview/
      # - name: Access Management & Overview
      #   url: /what/access-management-overview/

# How to use FICAM top level menu with dropdowns
  - name: How to use FICAM
    children:
      - name: Introduction
        url: /how/introduction/
      - name: Network Authentication
        url: /how/network-authentication/
      - name: Domain Controllers
        url: /how/domain-controllers/
      - name: Trust Store
        url: /how/trust-stores/
      - name: Account Linking
        url: /how/account-linking/
      - name: Group Policies and Enforcement
        url: /how/group-policies/
      - name: Network Tuning
        url: /how/network-tuning/
      - name: Local Certification Authority
        url: /how/certificate-authority/
      - name: Authentication Assurance
        url: /how/authentication-assurance/
      - name: PIV Authentication on macOS
        url: /how/piv-athentication-macos/
      - name: Troubleshooting PIV Logon
        url: /how/troubleshooting/ 
      # - name: Windows Domain Account Pairing
      #   url: /how/windows-domain-pairing/ 

# Who FICAM is For? top level menu with dropdowns
  - name: Who is FICAM For?
    children:
      - name: New? Get Started
        url: /who/new-get-started/
      - name: Technical Leads and Team Members
        url: /who/technical-leads-and-team-members/
      - name: PACS
        url: /who/pacs/
      - name: Vendors
        url: /who/vendors/
      - name: Acquisition Professionals
        url: /who/acquisition-professionals/
      - name: Program Manager
        url: /who/program-manager/
  
  # FICAM University page
  - name: University
    description: University
    url: /university/

  # FAQ page
  - name: FAQs
    description: Frequently Asked Questions
    url: /faq/

secondary_navigation:
  - name: Contact Us
    url: /contact-us/
  - name: About Us
    url: /about-us/
  - name: Contribute
    url: /contribute/

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:

  # You should not change this.
  endpoint: https://search.usa.gov

  # replace this with your search.gov account
  affiliate: idmprod

  # replace with your access key
  access_key: zCEoL5u4U5XFzfFSxy8y4Iz6vdtTjsb4U539L_rgDTM=

  # this renders the results within the page instead of sending to user to search.gov
  inline: false

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################

collections:
  why:
    output: true
    permalink: /why/:path/
  what:
    output: true
    permalink: /what/:path/
  how:
    output: true
    permalink: /how/:path/
  who:
    output: true
    permalink: /who/:path/
  university:
    output: true
    permalink: /university/:path/   
  faq:
    output: true
    permalink: /faq/:path/ 
  rss:
    output: true
    permalink: /news/:path/ 
  playbooks:
    output: true
    permalink: /playbooks/:path/ 

  # (Old, keep for ref) buy: 
  #   output: true
  #   permalink: /buy/:path/
  # sell:
  #   output: true
  #   permalink: /sell/:path/
  # governance:
  #   output: true
  #   permalink: /governance/:path/

  pages:
    output: true
    permalink: /:path/

permalink: pretty

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: "posts"
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 3
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: "/page/:num/" # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ":title - page :num"
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: "date"
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: "posts"
  # Optional, the default tag to use, omit to disable
  tag: ""
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ""
  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html
  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: "index.html"

exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - degit.json
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - staging-ficam-playbooks
assets:
  autoprefixer:
    browsers:
      - "> 2%"
      - "last 2 versions"
      - "IE 11"
      - "not dead"
  sources:
  ## Updated to @uswds 3.0
    - node_modules/@uswds/uswds/dist/css
    - node_modules/@uswds/uswds/dist/fonts
    - node_modules/@uswds/uswds/dist/img
    - node_modules/@uswds/uswds/dist/img/favicons
    - node_modules/@uswds/uswds/dist/img/material-icons
    - node_modules/@uswds/uswds/dist/img/usa-icons
    - node_modules/@uswds/uswds/dist/img/usa-icons-bg
    - node_modules/@uswds/uswds/dist/img/uswds-icons
    - node_modules/@uswds/uswds/dist/js
    - node_modules/@uswds/uswds/dist/scss
    - node_modules/@uswds/uswds/dist/theme
    - node_modules/@uswds/uswds/packages
    - node_modules/netlify-cms/dist
