# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

##########################################################################################
# Be sure to edit the values below
##########################################################################################

# title: IDManagement.gov (changed to use just IDManagement without the .gov) 
title: IDManagement
email: icam@gsa.gov
description: IDManagement.gov is a collaboration between the Federal CIO Council and GSA to develop and share leading practices in protecting federal IT systems.
baseurl: ""
repourl: "https://github.com/GSA/idmanagement.gov"

#for site map search
url: https://www.idmanagement.gov

# GitHub information
# This is used for adding an edit this page link to the footer
github_info:
  organization: GSA
  repository: idmanagement.gov
  default_branch: federalist-pages

# Twitter handle. Only the handle, not the URL.
# twitter: 18F
url: "https://www.idmanagement.gov"

dap:
  agency: GSA

  # Optional
  # subagency: your-subagency

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: Home
    url: /
  - name: Understand FICAM
    children:
      - name: FICAM Architecture
        url: /arch/
      - name: Zero Trust
        url: /zero-trust/
      - name: GSA ICAM Solutions Roadmap
        url: /icamsolutions/
  - name: Partners
    children:
      - name: Vendors
        url: /vendors/
      - name: Acquisition Professionals
        url: /acquisition-professionals/
      - name: Program Managers
        url: /program-managers/
  - name: Implement 
    children:
      - name: ICAM Configuration Guides
        url: /implement/
      - name: Distribute the FCPCA
        url: /implement/distribute-fcpca/
      - name: Smart Card Logon for Operating Systems
        url: /implement/scl-windows/
      - name: Certificate-based Authentication for Cloud
        url: /implement/whfb/
      - name: Use Smart Cards with Applications
        url: /implement/outlook/
      - name: FIDO2 and Web Authentication (Coming Soon!)
        url: /home/
      - name: FPKI Ecosystem Changes
        url: /fpki/notifications/
  - name: Coordination Functions
    children: 
      - name: FICAM Program
        url: /ficam/
      - name: Federal PKI Program
        url: /fpki/
      - name: FIPS 201 Evaluation Program
        url: /fips201ep/
      - name: GSA PKI SSP Program
        url: /pkissp/
  - name: Playbooks
    url: /playbooks/
  - name: University
    children: 
      - name: Introduction
        url: /university/
      - name: PKI 101
        url: /university/pki/
      - name: FPKI 101
        url: /university/fpki/
      - name: PIV 101
        url: /university/piv/
      - name: PIV-I 101
        url: /university/pivi/
      - name: PACS 101
        url: /university/pacs/
      - name: ICAM Policy Matrix
        url: /university/policy-matrix/

secondary_navigation:
  - name: Contact Us
    url: /contact-us/
  - name: About Us
    url: /about-us/
  - name: Contribute
    url: /contribute/

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:
  endpoint: https://search.usa.gov
  affiliate: idmprod
  access_key: zCEoL5u4U5XFzfFSxy8y4Iz6vdtTjsb4U539L_rgDTM=
  # this renders the results within the page instead of sending to user to search.gov
  inline: false

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################

collections:
  why:
    output: true
    permalink: /why/:path/
  arch:
    output: true
    permalink: /arch/:path/
  implement:
    output: true
    permalink: /implement/:path/
  partners:
    output: true
    permalink: /partners/:path/
  university:
    output: true
    permalink: /university/:path/   
  rss:
    output: true
    permalink: /rss/:path/ 
  playbooks:
    output: true
    permalink: /playbooks/:path/ 
  ficampmo:
    output: true
    permalink: /ficam/:path/

# Leaving in place: 
# Unsure of placement in new site.
  
  # sell:
  #   output: true
  #   permalink: /sell/:path/
  
  # Turned on for visibility until Combined 743 Playbook on Governance is complete

  pages:
    output: true
    permalink: /:path/

permalink: pretty

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: "posts"
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 3
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: "/page/:num/" # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ":title - page :num"
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: "date"
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: "posts"
  # Optional, the default tag to use, omit to disable
  tag: ""
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ""
  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html
  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: "index.html"

exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - degit.json
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - staging-ficam-playbooks
assets:
  autoprefixer:
    browsers:
      - "> 2%"
      - "last 2 versions"
      - "IE 11"
      - "not dead"
  sources:
  ## Updated to @uswds 3.0
    - node_modules/@uswds/uswds/dist/css
    - node_modules/@uswds/uswds/dist/fonts
    - node_modules/@uswds/uswds/dist/img
    - node_modules/@uswds/uswds/dist/img/favicons
    - node_modules/@uswds/uswds/dist/img/material-icons
    - node_modules/@uswds/uswds/dist/img/usa-icons
    - node_modules/@uswds/uswds/dist/img/usa-icons-bg
    - node_modules/@uswds/uswds/dist/img/uswds-icons
    - node_modules/@uswds/uswds/dist/js
    - node_modules/@uswds/uswds/dist/scss
    - node_modules/@uswds/uswds/dist/theme
    - node_modules/@uswds/uswds/packages
    - node_modules/netlify-cms/dist
